branches:
  only:
  - master
language: python
python:
- 2.7
install:
- pip install -r requirements.txt --use-mirrors
script:
- make html
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
  - secure: W9jdJcVLMok2QnSWn94bkBZL6yiP88paWBSQvj5pNwx6rMA/KAuAmEDTmxWCRpvte9CP1mTpPgNRwn7UhhmZsw4f1AKEAClxNbpbVUhiISW+LoVmlkhw//fp+qGplhun2ID9sJpfjsgun5Ue4+dcpvI2rHP17lC5ZgJBj3fx85M=
  - secure: EuleRVAaoed/C7mn6swpagRyfCf/ffhvavamXpqAx2KnbnAY1HX9sRFO8E2zCnjLLLz6ShgoWSNA4cloFnCbX41XbOnPXuUJkyBrV61X4twvVOcoDw/w2KVZfyhJ9umU5Ci4rr8kkGgIw8RPu8hFXP/0vVCk/I43t2K0KDshXrs=
  - secure: KE/wFyj6alpFJr7ebWmqCDWNTomYlvcqKEgIQ9lKMhFP8xQeZ/nxK+T0MIccyiQ0x3EfrOc40r7pp5vGbOwk0FZ7FGSnXFt035ltH8Sn76jR1hURXRV9uslJMQ/SycitQySuzlrOxybKBKMXyJkNhWX0nEndTNJ2VRInkawbFAF6uCFQ+7toPg04WVa+NLjML9Xrv2OuoUFOB9QYWC/johK2e2zLcuB8CXJHZ0knNtpXaAm/kSDDEzbG4GfCB9CdeIP3V8YP2MEjddOSS2eJH2QajsPM6wRcy1unZYOvlbtRQ3JZb5uVJtx4J5KVv7wn4SVmxKH208X9WtRYH7i0VmGQeDetfvuw31nSb7vDeBiJxSCJ2MXzra+bawFOtqnU4Kot+bC0wnY3INWupZbpbjBdyEN6XeQh4UtHGA8moYy5JWLddaXhmMRIYzAdgQg0TEF3cfkyQtovetbGJaxaNWnLBKFIkKMnSMgz2iQ6kxic53ScSjWyz7ac/utMsPU+obSzyk2PmC7C9NWCb3SZoF73mDeL7OP7Qkl7mI1JaUGteW4utlyqLAUDJ0Z9WF2wILj5uEyJdKoGlDgpxxE5E66fuR5HQ7sfmXTfFfzZMR+QoTZysvf+PURKCMrDniEM3KQAs5AE/IZTnAKrqKpzGNnP0z2/8WaFCTe7Nc8q1GM=
before_install:
- git submodule update --init --recursive
after_success: bash deploy.sh
