#!/bin/bash

# BogoMap-rutas is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# BogoMap-rutas is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with BogoMap-rutas.  If not, see http://www.gnu.org/licenses/.

pelican-quickstart <<EOF
.
BogoMap.co - Mapa del sistema de transporte de Bogota
Equipo BogoMap
es
y
http://rutas.bogomap.co
n
America/Bogota
y
y
n
n
n
n
n
y
y
EOF

