#!/bin/bash

rm -Rf themes/mombacho
git checkout themes/mombacho
rm Makefile develop_server.sh fabfile.py pelicanconf.py
git checkout pelicanconfOriginal.py
grep -v -e '^SITEURL' pelicanconfOriginal.py | sed -e 's/^#SITEURL/SITEURL/' > pelicanconfOriginal.py2
mv pelicanconfOriginal.py2 pelicanconfOriginal.py
LINE_START=$(awk '/Installs Pelican/{ print NR; exit }' .travis.yml)
LINE_END=$(awk '/Generates the package/{ print NR; exit }' .travis.yml)
LINE_COUNT=$(cat .travis.yml | wc -l)
echo "${LINE_START} ${LINE_END} ${LINE_COUNT}"
sed -e 's/^  - //' .travis.yml | tail -$((${LINE_COUNT}-${LINE_START})) | head -$((${LINE_END}-${LINE_START})) | source /dev/stdin

pelican
git checkout pelicanconfOriginal.py
cd output
python -m SimpleHTTPServer

