#!/bin/bash

# BogoMap-rutas is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# BogoMap-rutas is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with BogoMap-rutas.  If not, see http://www.gnu.org/licenses/.

rm -Rf themes/mombacho
git checkout themes/mombacho
rm Makefile develop_server.sh fabfile.py pelicanconf.py
git checkout pelicanconfOriginal.py
rm -Rf output
grep -v -e '^SITEURL' pelicanconfOriginal.py | sed -e 's/^#SITEURL/SITEURL/' > pelicanconfOriginal.py2
mv pelicanconfOriginal.py2 pelicanconfOriginal.py
LINE_START=$(awk '/Installs Pelican/{ print NR; exit }' .travis.yml)
LINE_END=$(awk '/Generates the package/{ print NR; exit }' .travis.yml)
LINE_COUNT=$(cat .travis.yml | wc -l)
echo "${LINE_START} ${LINE_END} ${LINE_COUNT}"
sed -e 's/^  - //' .travis.yml | tail -$((${LINE_COUNT}-${LINE_START})) | head -$((${LINE_END}-${LINE_START})) | source /dev/stdin

pelican
git checkout pelicanconfOriginal.py
cd output
python -m SimpleHTTPServer

